### ISSUE TITLE
Failure in better_mktemp() does not abort script

### ISSUE THREAD

**Issue by efung** [outlook/gifcap#1]
My machine is Mac OS 10.12.2 with Homebrew installed, in particular, the `coreutils` package, which provides the GNU `mktemp`. When I execute `gifcap`, the `mktemp` call fails, but I get the following:

```
$ gifcap
mktemp: too few X's in template ‘screencap’
mv: missing destination file operand after '.mp4'
Try 'mv --help' for more information.
mktemp: too few X's in template ‘palette’
mv: missing destination file operand after '.png'
Try 'mv --help' for more information.
basename: missing operand
Try 'basename --help' for more information.
Recording, end with CTRL+C
Unable to open '/sdcard/': Is a directory
[  0%] /sdcard/Download/f3de0bee-7693-4018-ac0e-66b2adf52e2e.apk: 36%^C
```

This ends up executing:

    adb pull /sdcard

which starts to pull *everything* off your device!

**Comment by benjamin-bader** [comment]
Haha, that's different!  Thanks for the PR, which is now merged.

**Comment by efung** [comment]
​Well, the PR doesn't address the wider issue, since I would expect the
script to abort, if any of its subroutines failed.

**Comment by efung** [comment]
Additional error handling might be simple to achieve via `set -u` and/or `set -e`:
http://www.davidpashley.com/articles/writing-robust-shell-scripts/#id2382181

**Comment by benjamin-bader** [comment]
Good idea.  I've added both switches in `master`.

**Comment by benjamin-bader** [comment]
Do you still see problems with errors not aborting the script?  I'm hopeful that I've stamped those out; if you still see problems in the latest version (`brew install gifcap`), please do let me know.  Thanks!
