### ISSUE TITLE
Homebrew!

### ISSUE THREAD

**Issue by ZacSweers** [outlook/gifcap#3]
(proposal)

**Comment by benjamin-bader** [comment]
I agree!  Give more stars and forks, and it'll happen!

(they require 20 of each, I believe, as a minimum notability bar before accepting a formula)

**Comment by benjamin-bader** [comment]
actual requirements:
```
❯ brew audit --new-formula gifcap
gifcap:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
Error: 2 problems in 1 formula
```

**Comment by hidroh** [comment]
Maybe go for a tap? https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by benjamin-bader** [comment]
We just hit 50 stars, and now `brew audit`'s only complaint is that this repo is too new, which will of course resolve itself in time.  I think we're good for getting into Homebrew proper, but maybe I'll see about a tap if there's time over the holidays.

**Comment by ZacSweers** [comment]
\o/

**Comment by benjamin-bader** [comment]
The waiting period is over - PR for homebrew-core is open:
https://github.com/Homebrew/homebrew-core/pull/9133

**Comment by benjamin-bader** [comment]
Hooray!  We're in Homebrew, as of 21:30ish today.
