### ISSUE TITLE
Homebrew Installing Issue

### ISSUE THREAD

**Issue by Stardustvalley** [outlook/gifcap#4]
I recently tried to install Wine with Homebrew but at the end of it it gave me this error:

==> ./configure --prefix=/usr/local/Cellar/sane-backends/1.0.25_1 --localstatedi
==> make
Last 15 lines from /Users/SelzAt/Library/Logs/Homebrew/sane-backends/02.make:
tail: /Users/SelzAt/Library/Logs/Homebrew/sane-backends/02.make: No such file or directory
Error: No such file or directory - /Users/SelzAt/Library/Logs/Homebrew/sane-backends/config.log

Can someone tell me what the problem is or how I can solve it?

**Comment by benjamin-bader** [comment]
Hi, I think you landed in the wrong Github - we aren't Homebrew, we're Microsoft Outlook.

Try asking at stackoverflow.com or at https://github.com/homebrew/homebrew-core.
